# Generated by Django 5.1.6 on 2025-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('custom_admin', 'Custom Admin'), ('operational_manager', 'Operational Manager'), ('franchise_owner', 'Franchise Owner'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=30),
        ),
    ]
