# Generated by Django 5.1.6 on 2025-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('custom_admin', 'Custom Admin'), ('operational_manager', 'Operational Manager'), ('franchise_owner', 'Franchise Owner'), ('teacher', 'Teacher'), ('student', 'Student'), ('acadamics_head', 'acadamics_head')], max_length=30),
        ),
    ]
